scorecard:
  # Setting a global scorecard option
  output: json
  plugins:
    # `basic` tests configured to test the CRs
    - basic:
        cr-manifest:
          - "deploy/crds/operator.ibm.com_v1alpha1_metering_cr.yaml"
          - "deploy/crds/operator.ibm.com_v1alpha1_meteringmulticloudui_cr.yaml"
          - "deploy/crds/operator.ibm.com_v1alpha1_meteringsender_cr.yaml"
          - "deploy/crds/operator.ibm.com_v1alpha1_meteringui_cr.yaml"
    # `olm` tests configured to test the CRs
    - olm:
        cr-manifest:
          - "deploy/crds/operator.ibm.com_v1alpha1_metering_cr.yaml"
          - "deploy/crds/operator.ibm.com_v1alpha1_meteringmulticloudui_cr.yaml"
          - "deploy/crds/operator.ibm.com_v1alpha1_meteringsender_cr.yaml"
          - "deploy/crds/operator.ibm.com_v1alpha1_meteringui_cr.yaml"
        csv-path: "deploy/olm-catalog/ibm-metering-operator/3.5.0/ibm-metering-operator.v3.5.0.clusterserviceversion.yaml"
