apiVersion: operator.ibm.com/v1alpha1
kind: Metering
metadata:
  name: example-metering
spec:
  # Add fields here
  version: "3.5.0"
  imageRegistry: hyc-cloud-private-edge-docker-local.artifactory.swg-devops.com/ibmcom-amd64
  #imageTagPostfix: "-20200114"
  iamNamespace: kube-system
  multiCloudReceiverEnabled: false
  mongodb:
    host: mongodb
    port: "27017"
    usernameSecret: icp-mongodb-admin
    usernameKey: user
    passwordSecret: icp-mongodb-admin
    passwordKey: password
    clustercertssecret: cluster-ca-cert
    clientcertssecret: icp-mongodb-client-cert
  external:
    clusterName: mycluster
