apiVersion: operator.ibm.com/v1alpha1
kind: Metering
metadata:
  name: metering
spec:
  version: "3.5.1"
  imageRegistry: quay.io/opencloudio
  iamNamespace: ibm-common-services
  multiCloudReceiverEnabled: false
  mongodb:
    host: mongodb
    port: 27017
    usernameSecret: icp-mongodb-admin
    usernameKey: user
    passwordSecret: icp-mongodb-admin
    passwordKey: password
    clustercertssecret: mongodb-root-ca-cert
    clientcertssecret: icp-mongodb-client-cert
