apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: meterings.operator.ibm.com
spec:
  group: operator.ibm.com
  names:
    kind: Metering
    listKind: MeteringList
    plural: meterings
    singular: metering
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      description: Metering is the Schema for the meterings API
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          description: MeteringSpec defines the desired state of Metering
          properties:
            dm:
              description: MeteringSpecDataManager defines the metering-datamanager
                configuration in the the metering spec
              properties:
                imageRegistry:
                  type: string
                imageTagPostfix:
                  type: string
              type: object
            external:
              description: MeteringSpecExternal defines the external cluster configuration
                in the the metering spec
              properties:
                cfcRouterUrl:
                  type: string
                clusterIP:
                  type: string
                clusterName:
                  type: string
                clusterPort:
                  type: string
              type: object
            mongodb:
              description: MeteringSpecMongoDB defines the MongoDB configuration in
                the the metering spec
              properties:
                clientcertssecret:
                  type: string
                clustercertssecret:
                  type: string
                host:
                  type: string
                passwordKey:
                  type: string
                passwordSecret:
                  type: string
                port:
                  type: string
                usernameKey:
                  type: string
                usernameSecret:
                  type: string
              type: object
            operatorVersion:
              description: 'INSERT ADDITIONAL SPEC FIELDS - desired state of cluster
                Important: Run "operator-sdk generate k8s" to regenerate code after
                modifying this file Add custom validation using kubebuilder tags:
                https://book-v1.book.kubebuilder.io/beyond_basics/generating_crd.html'
              type: string
            reader:
              description: MeteringSpecReader defines the metering-reader configuration
                in the the metering spec
              properties:
                imageRegistry:
                  type: string
                imageTagPostfix:
                  type: string
              type: object
          type: object
        status:
          description: MeteringStatus defines the observed state of Metering
          properties:
            nodes:
              description: 'INSERT ADDITIONAL STATUS FIELD - define observed state
                of cluster Important: Run "operator-sdk generate k8s" to regenerate
                code after modifying this file Add custom validation using kubebuilder
                tags: https://book-v1.book.kubebuilder.io/beyond_basics/generating_crd.html
                Nodes are the names of the metering pods'
              items:
                type: string
              type: array
          required:
          - nodes
          type: object
      type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
