apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ibm-metering-operator-cluster
rules:
#required by operator to create certificates
- apiGroups: ["certmanager.k8s.io"]
  resources: ["clusterissuers"]
  verbs: ["use"]
#required by reader to meter pods, clusters, pvcs (configmaps for mcmreader)
#- apiGroups: [""]
#  resources: ["namespaces", "pods", "nodes", "nodes/proxy", "configmaps", "persistentvolumes", "persistentvolumeclaims"]
#  verbs: ["get", "list"]
#required by mcmreader to list clusters
#- apiGroups: ["mcm.ibm.com"]
#  resources: ["clusterstatuses",]
#  verbs: ["get", "list"]
# The read permissions were expanded to all objects because of metering
# support to read metering annotations from the meta data of Custom Resource
# objects.  Since we cannot know all Kinds the role was expanded for all
# apiGroups and resources
- apiGroups: ["*"]
  resources: ["*"]
  verbs: ["get", "list"]
