apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: ibm-metering-operator-cluster
subjects:
- kind: ServiceAccount
  name: ibm-metering-operator
  namespace: ibm-metering-operator
roleRef:
    kind: ClusterRole
    name: ibm-metering-operator-cluster
    apiGroup: rbac.authorization.k8s.io