apiVersion: apps/v1
kind: Deployment
metadata:
  name: ibm-metering-operator
  labels:
    app.kubernetes.io/instance: "ibm-metering-operator"
    app.kubernetes.io/managed-by: "ibm-metering-operator"
    app.kubernetes.io/name: "ibm-metering"
spec:
  replicas: 1
  selector:
    matchLabels:
      name: ibm-metering-operator
  template:
    metadata:
      labels:
        name: ibm-metering-operator
        app.kubernetes.io/instance: "ibm-metering-operator"
        app.kubernetes.io/managed-by: "ibm-metering-operator"
        app.kubernetes.io/name: "ibm-metering"
      annotations:
        productName: IBM Cloud Platform Common Services
        productID: "068a62892a1e4db39641342e592daa25"
        productMetric: FREE
    spec:
      serviceAccountName: ibm-metering-operator
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: beta.kubernetes.io/arch
                operator: In
                values:
                - amd64
                - ppc64le
                - s390x
      hostIPC: false
      hostNetwork: false
      hostPID: false
      containers:
        - name: ibm-metering-operator
          # Replace this with the built image name
          image: quay.io/opencloudio/ibm-metering-operator:3.8.1
          command:
          - ibm-metering-operator
          imagePullPolicy: Always
          env:
            - name: IMAGE_SHA_OR_TAG_DM
              value: sha256:bb5d0ea92bbbc784abdc0bc01d0849ccb2010523a261ddc47a56a514575e3115
            - name: IMAGE_SHA_OR_TAG_UI
              value: sha256:5a9834c4be40f0ade4fffb68b455d41a91b29dccde49f5c41a62852f4fedca20
            - name: IMAGE_SHA_OR_TAG_MCMUI
              value: sha256:86b37299a3a1549b588f7d4a0e1b6e252afd27fc1b764b28b2fe4eb373414ff5
            - name: IMAGE_SHA_OR_TAG_REPORT
              value: sha256:4cae536b1d67b45b19de16d3b15ede9e5afacb1dfc08ec41c8c6c6705e96df04
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "ibm-metering-operator"
            - name: SA_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.serviceAccountName
          resources:
            limits:
              cpu: 100m
              memory: 300Mi
            requests:
              cpu: 10m
              memory: 50Mi
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
              - ALL
            privileged: false
            readOnlyRootFilesystem: true
            runAsNonRoot: true
