apiVersion: apps/v1
kind: Deployment
metadata:
  name: ibm-metering-operator
  labels:
    app.kubernetes.io/instance: "ibm-metering-operator"
    app.kubernetes.io/managed-by: "ibm-metering-operator"
    app.kubernetes.io/name: "ibm-metering"
spec:
  replicas: 1
  selector:
    matchLabels:
      name: ibm-metering-operator
  template:
    metadata:
      labels:
        name: ibm-metering-operator
        app.kubernetes.io/instance: "ibm-metering-operator"
        app.kubernetes.io/managed-by: "ibm-metering-operator"
        app.kubernetes.io/name: "ibm-metering"
      annotations:
        productName: IBM Cloud Platform Common Services
        productID: "068a62892a1e4db39641342e592daa25"
        productMetric: FREE
    spec:
      serviceAccountName: ibm-metering-operator
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: beta.kubernetes.io/arch
                operator: In
                values:
                - amd64
                - ppc64le
                - s390x
      hostIPC: false
      hostNetwork: false
      hostPID: false
      containers:
        - name: ibm-metering-operator
          # Replace this with the built image name
          image: quay.io/opencloudio/ibm-metering-operator:3.8.2
          command:
          - ibm-metering-operator
          imagePullPolicy: Always
          env:
            - name: IMAGE_SHA_OR_TAG_DM
              value: sha256:a87f19337295fbc294298be8c362f85202f63d9675e22d8d84890f94c6fb4410
            - name: IMAGE_SHA_OR_TAG_UI
              value: sha256:a17db4f10d0f40cb624299d3ca768ce087da8414b46843f4403767776582ba3d
            - name: IMAGE_SHA_OR_TAG_MCMUI
              value: sha256:c2cce954e4d4636ef128ab063ca3488896303ad195e416d36abb5019c8761952
            - name: IMAGE_SHA_OR_TAG_REPORT
              value: sha256:5c516cc208c23493490a225291b1d7f0a408feea13b08e0b918046143bf15681
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "ibm-metering-operator"
            - name: SA_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.serviceAccountName
          resources:
            limits:
              cpu: 100m
              memory: 300Mi
            requests:
              cpu: 10m
              memory: 50Mi
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
              - ALL
            privileged: false
            readOnlyRootFilesystem: true
            runAsNonRoot: true
