apiVersion: apps/v1
kind: Deployment
metadata:
  name: ibm-metering-operator
  labels:
    app.kubernetes.io/instance: "ibm-metering-operator"
    app.kubernetes.io/managed-by: "ibm-metering-operator"
    app.kubernetes.io/name: "ibm-metering"
spec:
  replicas: 1
  selector:
    matchLabels:
      name: ibm-metering-operator
  template:
    metadata:
      labels:
        name: ibm-metering-operator
        app.kubernetes.io/instance: "ibm-metering-operator"
        app.kubernetes.io/managed-by: "ibm-metering-operator"
        app.kubernetes.io/name: "ibm-metering"
      annotations:
        productName: IBM Cloud Platform Common Services
        productID: "068a62892a1e4db39641342e592daa25"
        productVersion: "3.3.0"
        productMetric: FREE
    spec:
      serviceAccountName: ibm-metering-operator
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: beta.kubernetes.io/arch
                operator: In
                values:
                - amd64
                - ppc64le
                - s390x
      hostIPC: false
      hostNetwork: false
      hostPID: false
      containers:
        - name: ibm-metering-operator
          # Replace this with the built image name
          image: quay.io/opencloudio/ibm-metering-operator:latest
          command:
          - ibm-metering-operator
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "ibm-metering-operator"
            - name: SA_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.serviceAccountName              
          resources:
            limits:
              cpu: 20m
              memory: 40Mi
            requests:
              cpu: 10m
              memory: 25Mi
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
              - ALL
            privileged: false
            readOnlyRootFilesystem: true
            runAsNonRoot: true
