kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: ibm-metering-operator
subjects:
- kind: ServiceAccount
  name: ibm-metering-operator
roleRef:
  kind: Role
  name: ibm-metering-operator
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: ibm-metering-operator-cluster
subjects:
- kind: ServiceAccount
  name: ibm-metering-operator
  namespace: ibm-metering-operator
roleRef:
  kind: ClusterRole
  name: ibm-metering-operator-cluster
  apiGroup: rbac.authorization.k8s.io