apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  creationTimestamp: null
  name: ibm-metering-operator
  labels:
    app.kubernetes.io/instance: "ibm-metering-operator"
    app.kubernetes.io/managed-by: "ibm-metering-operator"
    app.kubernetes.io/name: "ibm-metering"
rules:
- apiGroups:
  - ""
  resources:
  - pods
  - services
  - services/finalizers
  - endpoints
  - persistentvolumeclaims
  - events
  - configmaps
  - secrets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps
  resources:
  - deployments
  - daemonsets
  - replicasets
  - statefulsets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - monitoring.coreos.com
  resources:
  - servicemonitors
  verbs:
  - get
  - create
- apiGroups:
  - apps
  resourceNames:
  - ibm-metering-operator
  resources:
  - deployments/finalizers
  verbs:
  - update
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
- apiGroups:
  - apps
  resources:
  - replicasets
  - deployments
  verbs:
  - get
- apiGroups:
  - operator.ibm.com
  resources:
  - '*'
  - meteringuis
  - meteringmulticlouduis
  - meteringsenders
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - certmanager.k8s.io
  resources:
  - '*'
  - certificates
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - networking.k8s.io
  - extensions
  resources:
  - '*'
  - ingresses
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - route.openshift.io
  resources:
  - routes
  - routes/custom-host
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch 
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ibm-metering-operator
  labels:
    app.kubernetes.io/instance: "ibm-metering-operator"
    app.kubernetes.io/managed-by: "ibm-metering-operator"
    app.kubernetes.io/name: "ibm-metering"
rules:
# required by operator to get appDomain in IngressController
- apiGroups:
  - "operator.openshift.io"
  resources:
  - ingresscontrollers
  verbs:
  - get
# required by meteringreportserver to create APIService
- apiGroups:
  - authorization.k8s.io
  resources:
  - subjectaccessreviews
  verbs:
  - create
# required by meteringreportserver to create APIService
- apiGroups:
  - apiregistration.k8s.io
  resources:
  - apiservices
  verbs:
  - create
  - list
  - watch
# required by meteringreportserver
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - watch
# required by operator to update meteringreportserver CR at cluster scope
- apiGroups:
  - operator.ibm.com
  resources:
  - meteringreportservers
  - meteringreportservers/status
  - meteringreportservers/finalizers
  verbs:
  - create
  - delete
  - get
  - list
  - update
  - watch
# required by reader to meter pods, clusters, pvcs (configmaps for mcmreader)
- apiGroups:
  - ""
  resources:
  - namespaces
  - pods
  - nodes
  - nodes/proxy
  - configmaps
  - persistentvolumes
  - persistentvolumeclaims
  verbs:
  - get
  - list
# required by sender to get MCM hub kube config
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
# required by mcmreader to list clusters
- apiGroups:
  - mcm.ibm.com
  resources:
  - clusterstatuses
  - leadervotes
  verbs:
  - get
  - list
# required by mcmreader to check RACM hub
- apiGroups:
  - operator.open-cluster-management.io
  resources:
  - multiclusterhubs
  verbs:
  - get
  - list
- apiGroups:
  - cluster.open-cluster-management.io
  resources:
  - managedclusters
  verbs:
  - get
  - list
- apiGroups:
  - internal.open-cluster-management.io
  resources:
  - managedclusterinfos
  verbs:
  - get
  - list
