apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: meterings.operator.ibm.com
  labels:
    app.kubernetes.io/instance: "ibm-metering-operator"
    app.kubernetes.io/managed-by: "ibm-metering-operator"
    app.kubernetes.io/name: "ibm-metering"
spec:
  group: operator.ibm.com
  names:
    kind: Metering
    listKind: MeteringList
    plural: meterings
    singular: metering
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      description: Metering is the Schema for the meterings API
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          description: MeteringSpec defines the desired state of Metering
          properties:
            clusterIssuer:
              type: string
            dataManager:
              description: MeteringSpecDM defines the DataManager configuration in
                the Metering spec
              properties:
                dm:
                  description: MeteringSpecResources defines the resource requirements
                    for the Metering containers
                  properties:
                    resources:
                      description: ResourceRequirements describes the compute resource
                        requirements.
                      properties:
                        limits:
                          additionalProperties:
                            type: string
                          description: 'Limits describes the maximum amount of compute
                            resources allowed. More info: https://kubernetes.io/docs/concepts/configuration/manage-compute-resources-container/'
                          type: object
                        requests:
                          additionalProperties:
                            type: string
                          description: 'Requests describes the minimum amount of compute
                            resources required. If Requests is omitted for a container,
                            it defaults to Limits if that is explicitly specified,
                            otherwise to an implementation-defined value. More info:
                            https://kubernetes.io/docs/concepts/configuration/manage-compute-resources-container/'
                          type: object
                      type: object
                  type: object
              type: object
            excludeSystemNamespaces:
              type: boolean
            iamNamespace:
              type: string
            imageRegistry:
              type: string
            imageTagPostfix:
              type: string
            mongodb:
              description: MeteringSpecMongoDB defines the MongoDB configuration in
                all the Metering specs
              properties:
                clientcertssecret:
                  type: string
                clustercertssecret:
                  type: string
                host:
                  type: string
                passwordKey:
                  type: string
                passwordSecret:
                  type: string
                port:
                  type: integer
                usernameKey:
                  type: string
                usernameSecret:
                  type: string
              required:
              - clientcertssecret
              - clustercertssecret
              - host
              - passwordKey
              - passwordSecret
              - port
              - usernameKey
              - usernameSecret
              type: object
            multiCloudReceiverEnabled:
              type: boolean
            reader:
              description: MeteringSpecRdr defines the Reader configuration in the
                Metering spec
              properties:
                rdr:
                  description: MeteringSpecResources defines the resource requirements
                    for the Metering containers
                  properties:
                    resources:
                      description: ResourceRequirements describes the compute resource
                        requirements.
                      properties:
                        limits:
                          additionalProperties:
                            type: string
                          description: 'Limits describes the maximum amount of compute
                            resources allowed. More info: https://kubernetes.io/docs/concepts/configuration/manage-compute-resources-container/'
                          type: object
                        requests:
                          additionalProperties:
                            type: string
                          description: 'Requests describes the minimum amount of compute
                            resources required. If Requests is omitted for a container,
                            it defaults to Limits if that is explicitly specified,
                            otherwise to an implementation-defined value. More info:
                            https://kubernetes.io/docs/concepts/configuration/manage-compute-resources-container/'
                          type: object
                      type: object
                  type: object
              type: object
            version:
              description: 'INSERT ADDITIONAL SPEC FIELDS - desired state of cluster
                Important: Run "operator-sdk generate k8s" to regenerate code after
                modifying this file Add custom validation using kubebuilder tags:
                https://book-v1.book.kubebuilder.io/beyond_basics/generating_crd.html'
              type: string
          required:
          - mongodb
          - version
          type: object
        status:
          description: MeteringStatus defines the observed state of each Metering
            service
          properties:
            podNames:
              description: 'INSERT ADDITIONAL STATUS FIELD - define observed state
                of cluster Important: Run "operator-sdk generate k8s" to regenerate
                code after modifying this file Add custom validation using kubebuilder
                tags: https://book-v1.book.kubebuilder.io/beyond_basics/generating_crd.html
                PodNames are the names of the metering pods'
              items:
                type: string
              type: array
            versions:
              properties:
                reconciled:
                  type: string
              required:
              - reconciled
              type: object
          required:
          - podNames
          type: object
      type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
