apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: |-
      [
        {
          "apiVersion": "operator.ibm.com/v1alpha1",
          "kind": "Metering",
          "metadata": {
            "name": "metering"
          },
          "spec": {
            "iamNamespace": "ibm-common-services",
            "imageRegistry": "hyc-cloud-private-edge-docker-local.artifactory.swg-devops.com/ibmcom-amd64",
            "mongodb": {
              "clientcertssecret": "icp-mongodb-client-cert",
              "clustercertssecret": "mongodb-root-ca-cert",
              "host": "mongodb",
              "passwordKey": "password",
              "passwordSecret": "icp-mongodb-admin",
              "port": 27017,
              "usernameKey": "user",
              "usernameSecret": "icp-mongodb-admin"
            },
            "multiCloudReceiverEnabled": false,
            "version": "3.5.0"
          }
        },
        {
          "apiVersion": "operator.ibm.com/v1alpha1",
          "kind": "MeteringMultiCloudUI",
          "metadata": {
            "name": "meteringmcmui"
          },
          "spec": {
            "commonHeaderNamespace": "ibm-common-services",
            "iamNamespace": "ibm-common-services",
            "imageRegistry": "hyc-cloud-private-edge-docker-local.artifactory.swg-devops.com/ibmcom-amd64",
            "ingressNamespace": "ibm-common-services",
            "mongodb": {
              "clientcertssecret": "icp-mongodb-client-cert",
              "clustercertssecret": "mongodb-root-ca-cert",
              "host": "mongodb",
              "passwordKey": "password",
              "passwordSecret": "icp-mongodb-admin",
              "port": 27017,
              "usernameKey": "user",
              "usernameSecret": "icp-mongodb-admin"
            },
            "replicas": 1,
            "version": "3.5.0"
          }
        },
        {
          "apiVersion": "operator.ibm.com/v1alpha1",
          "kind": "MeteringSender",
          "metadata": {
            "name": "meteringsender"
          },
          "spec": {
            "imageRegistry": "hyc-cloud-private-edge-docker-local.artifactory.swg-devops.com/ibmcom-amd64",
            "mongodb": {
              "clientcertssecret": "icp-mongodb-client-cert",
              "clustercertssecret": "mongodb-root-ca-cert",
              "host": "mongodb",
              "passwordKey": "password",
              "passwordSecret": "icp-mongodb-admin",
              "port": 27017,
              "usernameKey": "user",
              "usernameSecret": "icp-mongodb-admin"
            },
            "sender": {
              "clusterName": "mycluster",
              "clusterNamespace": "ibm-common-services",
              "hubKubeConfigSecret": "multicluster-endpoint/endpoint-connmgr-hub-kubeconfig"
            },
            "version": "3.5.0"
          }
        },
        {
          "apiVersion": "operator.ibm.com/v1alpha1",
          "kind": "MeteringUI",
          "metadata": {
            "name": "meteringui"
          },
          "spec": {
            "clusterName": "mycluster",
            "commonHeaderNamespace": "ibm-common-services",
            "iamNamespace": "ibm-common-services",
            "imageRegistry": "hyc-cloud-private-edge-docker-local.artifactory.swg-devops.com/ibmcom-amd64",
            "ingressNamespace": "ibm-common-services",
            "mongodb": {
              "clientcertssecret": "icp-mongodb-client-cert",
              "clustercertssecret": "mongodb-root-ca-cert",
              "host": "mongodb",
              "passwordKey": "password",
              "passwordSecret": "icp-mongodb-admin",
              "port": 27017,
              "usernameKey": "user",
              "usernameSecret": "icp-mongodb-admin"
            },
            "replicas": 1,
            "version": "3.5.0"
          }
        }
      ]
    capabilities: Basic Install
  name: ibm-metering-operator.v3.5.0
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - description: MeteringMultiCloudUI is the Schema for the meteringmulticlouduis
        API
      kind: MeteringMultiCloudUI
      name: meteringmulticlouduis.operator.ibm.com
      version: v1alpha1
      displayName: Metering multicloud user interface
    - description: Metering is the Schema for the meterings API
      kind: Metering
      name: meterings.operator.ibm.com
      version: v1alpha1
      displayName: Metering service
    - description: MeteringSender is the Schema for the meteringsenders API
      kind: MeteringSender
      name: meteringsenders.operator.ibm.com
      displayName: Metering multicloud sender
      version: v1alpha1
    - description: MeteringUI is the Schema for the meteringuis API
      kind: MeteringUI
      name: meteringuis.operator.ibm.com
      displayName: Metering user interface
      version: v1alpha1
  description: The metering operator manages the service used to meter workloads in
    a kubernetes cluster
  displayName: IBM Metering Operator
  install:
    spec:
      clusterPermissions:
      - rules:
        - apiGroups:
          - certmanager.k8s.io
          resources:
          - clusterissuers
          verbs:
          - use
        - apiGroups:
          - '*'
          resources:
          - '*'
          verbs:
          - get
          - list
        serviceAccountName: ibm-metering-operator-cluster
      deployments:
      - name: ibm-metering-operator
        spec:
          replicas: 1
          selector:
            matchLabels:
              name: ibm-metering-operator
          strategy: {}
          template:
            metadata:
              labels:
                name: ibm-metering-operator
            spec:
              containers:
              - command:
                - ibm-metering-operator
                env:
                - name: WATCH_NAMESPACE
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.annotations['olm.targetNamespaces']
                - name: POD_NAME
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.name
                - name: OPERATOR_NAME
                  value: ibm-metering-operator
                - name: SA_NAME
                  valueFrom:
                    fieldRef:
                      fieldPath: spec.serviceAccountName
                image: quay.io/opencloudio/ibm-metering-operator
                imagePullPolicy: Always
                name: ibm-metering-operator
                resources: {}
              serviceAccountName: ibm-metering-operator
      permissions:
      - rules:
        - apiGroups:
          - ""
          resources:
          - pods
          - services
          - services/finalizers
          - endpoints
          - persistentvolumeclaims
          - events
          - configmaps
          - secrets
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - apps
          resources:
          - deployments
          - daemonsets
          - replicasets
          - statefulsets
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - monitoring.coreos.com
          resources:
          - servicemonitors
          verbs:
          - get
          - create
        - apiGroups:
          - apps
          resourceNames:
          - ibm-metering-operator
          resources:
          - deployments/finalizers
          verbs:
          - update
        - apiGroups:
          - ""
          resources:
          - pods
          verbs:
          - get
        - apiGroups:
          - apps
          resources:
          - replicasets
          - deployments
          verbs:
          - get
        - apiGroups:
          - operator.ibm.com
          resources:
          - '*'
          - meteringuis
          - meteringmulticlouduis
          - meteringsenders
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - certmanager.k8s.io
          resources:
          - '*'
          - certificates
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - networking.k8s.io
          resources:
          - '*'
          - ingresses
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        serviceAccountName: ibm-metering-operator
    strategy: deployment
  installModes:
  - supported: true
    type: OwnNamespace
  - supported: true
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  maturity: alpha
  provider:
    name: IBM
  replaces: ibm-metering-operator.v0.0.0
  version: 3.5.0
